[package]
name = "umya-spreadsheet"
version = "0.4.7"
authors = ["MathNya <umya.net.info@gmail.com>"]
repository = "https://github.com/MathNya/umya-spreadsheet"
keywords = ["excel", "spreadsheet", "xlsx", "reader", "writer"]
license = "MIT"
readme = "README.md"
description = "umya-spreadsheet is a library written in pure Rust and read and write xlsx file."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = { version = "0.17", features = [ "serialize" ] }
zip = "0.5.6"
regex = "1.3.7"
md5 = "0.7.0"
lazy_static = "1.4.0"
thousands = "0.2.0"
onig = { version = "6.1.1", default-features = false }
chrono = "0.4.19"

[lib]
doctest = false
